name: Solar Theme
url: https://deathon2legs.git.io/
description: my portfolio site.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
